//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Final___Lppa.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento lista del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchasesByBuyerID", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType))]
        TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDResponse getPurchasesByBuyerID(TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchasesByBuyerID", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDResponse> getPurchasesByBuyerIDAsync(TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento lista del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchasesByDate", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType))]
        TP_Final___Lppa.ServiceReference1.getPurchasesByDateResponse getPurchasesByDate(TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchasesByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesByDateResponse> getPurchasesByDateAsync(TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento lista del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchasesByProductID", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType))]
        TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDResponse getPurchasesByProductID(TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchasesByProductID", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDResponse> getPurchasesByProductIDAsync(TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getPurchasesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchases", ReplyAction="*")]
        TP_Final___Lppa.ServiceReference1.getPurchasesResponse getPurchases(TP_Final___Lppa.ServiceReference1.getPurchasesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPurchases", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesResponse> getPurchasesAsync(TP_Final___Lppa.ServiceReference1.getPurchasesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPurchasesByBuyerIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPurchasesByBuyerID", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequestBody Body;
        
        public getPurchasesByBuyerIDRequest() {
        }
        
        public getPurchasesByBuyerIDRequest(TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPurchasesByBuyerIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int buyerId;
        
        public getPurchasesByBuyerIDRequestBody() {
        }
        
        public getPurchasesByBuyerIDRequestBody(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista, int buyerId) {
            this.lista = lista;
            this.buyerId = buyerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPurchasesByBuyerIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPurchasesByBuyerIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDResponseBody Body;
        
        public getPurchasesByBuyerIDResponse() {
        }
        
        public getPurchasesByBuyerIDResponse(TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPurchasesByBuyerIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesByBuyerIDResult;
        
        public getPurchasesByBuyerIDResponseBody() {
        }
        
        public getPurchasesByBuyerIDResponseBody(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesByBuyerIDResult) {
            this.getPurchasesByBuyerIDResult = getPurchasesByBuyerIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPurchasesByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPurchasesByDate", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequestBody Body;
        
        public getPurchasesByDateRequest() {
        }
        
        public getPurchasesByDateRequest(TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPurchasesByDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        public getPurchasesByDateRequestBody() {
        }
        
        public getPurchasesByDateRequestBody(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista, System.DateTime date) {
            this.lista = lista;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPurchasesByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPurchasesByDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.getPurchasesByDateResponseBody Body;
        
        public getPurchasesByDateResponse() {
        }
        
        public getPurchasesByDateResponse(TP_Final___Lppa.ServiceReference1.getPurchasesByDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPurchasesByDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesByDateResult;
        
        public getPurchasesByDateResponseBody() {
        }
        
        public getPurchasesByDateResponseBody(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesByDateResult) {
            this.getPurchasesByDateResult = getPurchasesByDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPurchasesByProductIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPurchasesByProductID", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequestBody Body;
        
        public getPurchasesByProductIDRequest() {
        }
        
        public getPurchasesByProductIDRequest(TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPurchasesByProductIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int productId;
        
        public getPurchasesByProductIDRequestBody() {
        }
        
        public getPurchasesByProductIDRequestBody(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista, int productId) {
            this.lista = lista;
            this.productId = productId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPurchasesByProductIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPurchasesByProductIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDResponseBody Body;
        
        public getPurchasesByProductIDResponse() {
        }
        
        public getPurchasesByProductIDResponse(TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPurchasesByProductIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesByProductIDResult;
        
        public getPurchasesByProductIDResponseBody() {
        }
        
        public getPurchasesByProductIDResponseBody(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesByProductIDResult) {
            this.getPurchasesByProductIDResult = getPurchasesByProductIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPurchasesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPurchases", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.getPurchasesRequestBody Body;
        
        public getPurchasesRequest() {
        }
        
        public getPurchasesRequest(TP_Final___Lppa.ServiceReference1.getPurchasesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getPurchasesRequestBody {
        
        public getPurchasesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPurchasesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPurchasesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.getPurchasesResponseBody Body;
        
        public getPurchasesResponse() {
        }
        
        public getPurchasesResponse(TP_Final___Lppa.ServiceReference1.getPurchasesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPurchasesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesResult;
        
        public getPurchasesResponseBody() {
        }
        
        public getPurchasesResponseBody(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesResult) {
            this.getPurchasesResult = getPurchasesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : TP_Final___Lppa.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<TP_Final___Lppa.ServiceReference1.WebServiceSoap>, TP_Final___Lppa.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDResponse TP_Final___Lppa.ServiceReference1.WebServiceSoap.getPurchasesByBuyerID(TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequest request) {
            return base.Channel.getPurchasesByBuyerID(request);
        }
        
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesByBuyerID(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista, int buyerId) {
            TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequest inValue = new TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequestBody();
            inValue.Body.lista = lista;
            inValue.Body.buyerId = buyerId;
            TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDResponse retVal = ((TP_Final___Lppa.ServiceReference1.WebServiceSoap)(this)).getPurchasesByBuyerID(inValue);
            return retVal.Body.getPurchasesByBuyerIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDResponse> TP_Final___Lppa.ServiceReference1.WebServiceSoap.getPurchasesByBuyerIDAsync(TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequest request) {
            return base.Channel.getPurchasesByBuyerIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDResponse> getPurchasesByBuyerIDAsync(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista, int buyerId) {
            TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequest inValue = new TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.getPurchasesByBuyerIDRequestBody();
            inValue.Body.lista = lista;
            inValue.Body.buyerId = buyerId;
            return ((TP_Final___Lppa.ServiceReference1.WebServiceSoap)(this)).getPurchasesByBuyerIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Final___Lppa.ServiceReference1.getPurchasesByDateResponse TP_Final___Lppa.ServiceReference1.WebServiceSoap.getPurchasesByDate(TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequest request) {
            return base.Channel.getPurchasesByDate(request);
        }
        
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesByDate(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista, System.DateTime date) {
            TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequest inValue = new TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequestBody();
            inValue.Body.lista = lista;
            inValue.Body.date = date;
            TP_Final___Lppa.ServiceReference1.getPurchasesByDateResponse retVal = ((TP_Final___Lppa.ServiceReference1.WebServiceSoap)(this)).getPurchasesByDate(inValue);
            return retVal.Body.getPurchasesByDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesByDateResponse> TP_Final___Lppa.ServiceReference1.WebServiceSoap.getPurchasesByDateAsync(TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequest request) {
            return base.Channel.getPurchasesByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesByDateResponse> getPurchasesByDateAsync(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista, System.DateTime date) {
            TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequest inValue = new TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.getPurchasesByDateRequestBody();
            inValue.Body.lista = lista;
            inValue.Body.date = date;
            return ((TP_Final___Lppa.ServiceReference1.WebServiceSoap)(this)).getPurchasesByDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDResponse TP_Final___Lppa.ServiceReference1.WebServiceSoap.getPurchasesByProductID(TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequest request) {
            return base.Channel.getPurchasesByProductID(request);
        }
        
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchasesByProductID(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista, int productId) {
            TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequest inValue = new TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequestBody();
            inValue.Body.lista = lista;
            inValue.Body.productId = productId;
            TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDResponse retVal = ((TP_Final___Lppa.ServiceReference1.WebServiceSoap)(this)).getPurchasesByProductID(inValue);
            return retVal.Body.getPurchasesByProductIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDResponse> TP_Final___Lppa.ServiceReference1.WebServiceSoap.getPurchasesByProductIDAsync(TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequest request) {
            return base.Channel.getPurchasesByProductIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDResponse> getPurchasesByProductIDAsync(TP_Final___Lppa.ServiceReference1.ArrayOfAnyType lista, int productId) {
            TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequest inValue = new TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.getPurchasesByProductIDRequestBody();
            inValue.Body.lista = lista;
            inValue.Body.productId = productId;
            return ((TP_Final___Lppa.ServiceReference1.WebServiceSoap)(this)).getPurchasesByProductIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Final___Lppa.ServiceReference1.getPurchasesResponse TP_Final___Lppa.ServiceReference1.WebServiceSoap.getPurchases(TP_Final___Lppa.ServiceReference1.getPurchasesRequest request) {
            return base.Channel.getPurchases(request);
        }
        
        public TP_Final___Lppa.ServiceReference1.ArrayOfAnyType getPurchases() {
            TP_Final___Lppa.ServiceReference1.getPurchasesRequest inValue = new TP_Final___Lppa.ServiceReference1.getPurchasesRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.getPurchasesRequestBody();
            TP_Final___Lppa.ServiceReference1.getPurchasesResponse retVal = ((TP_Final___Lppa.ServiceReference1.WebServiceSoap)(this)).getPurchases(inValue);
            return retVal.Body.getPurchasesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesResponse> TP_Final___Lppa.ServiceReference1.WebServiceSoap.getPurchasesAsync(TP_Final___Lppa.ServiceReference1.getPurchasesRequest request) {
            return base.Channel.getPurchasesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.getPurchasesResponse> getPurchasesAsync() {
            TP_Final___Lppa.ServiceReference1.getPurchasesRequest inValue = new TP_Final___Lppa.ServiceReference1.getPurchasesRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.getPurchasesRequestBody();
            return ((TP_Final___Lppa.ServiceReference1.WebServiceSoap)(this)).getPurchasesAsync(inValue);
        }
    }
}
