//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Final___Lppa.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compras", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Compras : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.DateTime FechaCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TP_Final___Lppa.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TP_Final___Lppa.ServiceReference1.Productos ProductosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime FechaCompra {
            get {
                return this.FechaCompraField;
            }
            set {
                if ((this.FechaCompraField.Equals(value) != true)) {
                    this.FechaCompraField = value;
                    this.RaisePropertyChanged("FechaCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TP_Final___Lppa.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TP_Final___Lppa.ServiceReference1.Productos Productos {
            get {
                return this.ProductosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductosField, value) != true)) {
                    this.ProductosField = value;
                    this.RaisePropertyChanged("Productos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        private TP_Final___Lppa.ServiceReference1.UserType userTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] dvhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public TP_Final___Lppa.ServiceReference1.UserType userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((this.userTypeField.Equals(value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] dvh {
            get {
                return this.dvhField;
            }
            set {
                if ((object.ReferenceEquals(this.dvhField, value) != true)) {
                    this.dvhField = value;
                    this.RaisePropertyChanged("dvh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Productos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://tempuri.org/")]
    public enum UserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        webmaster = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        user = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FiltradoComprasSoap")]
    public interface FiltradoComprasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento comprador del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompras", ReplyAction="*")]
        TP_Final___Lppa.ServiceReference1.GetComprasResponse GetCompras(TP_Final___Lppa.ServiceReference1.GetComprasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompras", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.GetComprasResponse> GetComprasAsync(TP_Final___Lppa.ServiceReference1.GetComprasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComprasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompras", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.GetComprasRequestBody Body;
        
        public GetComprasRequest() {
        }
        
        public GetComprasRequest(TP_Final___Lppa.ServiceReference1.GetComprasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetComprasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fechaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fechaFin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string comprador;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> idProducto;
        
        public GetComprasRequestBody() {
        }
        
        public GetComprasRequestBody(System.DateTime fechaInicio, System.DateTime fechaFin, string comprador, System.Nullable<int> idProducto) {
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.comprador = comprador;
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComprasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComprasResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_Final___Lppa.ServiceReference1.GetComprasResponseBody Body;
        
        public GetComprasResponse() {
        }
        
        public GetComprasResponse(TP_Final___Lppa.ServiceReference1.GetComprasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetComprasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_Final___Lppa.ServiceReference1.Compras[] GetComprasResult;
        
        public GetComprasResponseBody() {
        }
        
        public GetComprasResponseBody(TP_Final___Lppa.ServiceReference1.Compras[] GetComprasResult) {
            this.GetComprasResult = GetComprasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiltradoComprasSoapChannel : TP_Final___Lppa.ServiceReference1.FiltradoComprasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiltradoComprasSoapClient : System.ServiceModel.ClientBase<TP_Final___Lppa.ServiceReference1.FiltradoComprasSoap>, TP_Final___Lppa.ServiceReference1.FiltradoComprasSoap {
        
        public FiltradoComprasSoapClient() {
        }
        
        public FiltradoComprasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiltradoComprasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiltradoComprasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiltradoComprasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_Final___Lppa.ServiceReference1.GetComprasResponse TP_Final___Lppa.ServiceReference1.FiltradoComprasSoap.GetCompras(TP_Final___Lppa.ServiceReference1.GetComprasRequest request) {
            return base.Channel.GetCompras(request);
        }
        
        public TP_Final___Lppa.ServiceReference1.Compras[] GetCompras(System.DateTime fechaInicio, System.DateTime fechaFin, string comprador, System.Nullable<int> idProducto) {
            TP_Final___Lppa.ServiceReference1.GetComprasRequest inValue = new TP_Final___Lppa.ServiceReference1.GetComprasRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.GetComprasRequestBody();
            inValue.Body.fechaInicio = fechaInicio;
            inValue.Body.fechaFin = fechaFin;
            inValue.Body.comprador = comprador;
            inValue.Body.idProducto = idProducto;
            TP_Final___Lppa.ServiceReference1.GetComprasResponse retVal = ((TP_Final___Lppa.ServiceReference1.FiltradoComprasSoap)(this)).GetCompras(inValue);
            return retVal.Body.GetComprasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.GetComprasResponse> TP_Final___Lppa.ServiceReference1.FiltradoComprasSoap.GetComprasAsync(TP_Final___Lppa.ServiceReference1.GetComprasRequest request) {
            return base.Channel.GetComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_Final___Lppa.ServiceReference1.GetComprasResponse> GetComprasAsync(System.DateTime fechaInicio, System.DateTime fechaFin, string comprador, System.Nullable<int> idProducto) {
            TP_Final___Lppa.ServiceReference1.GetComprasRequest inValue = new TP_Final___Lppa.ServiceReference1.GetComprasRequest();
            inValue.Body = new TP_Final___Lppa.ServiceReference1.GetComprasRequestBody();
            inValue.Body.fechaInicio = fechaInicio;
            inValue.Body.fechaFin = fechaFin;
            inValue.Body.comprador = comprador;
            inValue.Body.idProducto = idProducto;
            return ((TP_Final___Lppa.ServiceReference1.FiltradoComprasSoap)(this)).GetComprasAsync(inValue);
        }
    }
}
